# Generated by Django 4.2.10 on 2024-02-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employments',
            name='clients',
        ),
    ]
