# Generated by Django 4.2.10 on 2024-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employments', '0002_remove_employments_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employments',
            name='description',
            field=models.TextField(),
        ),
    ]
