# Generated by Django 4.2.10 on 2024-02-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
