# Generated by Django 4.2.10 on 2024-02-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submitemployment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitemployment',
            name='motivation_on_employment',
            field=models.TextField(),
        ),
    ]
