# Generated by Django 4.2.10 on 2024-02-27 00:03

from django.db import migrations, models
import submitemployment.models


class Migration(migrations.Migration):

    dependencies = [
        ('submitemployment', '0002_alter_submitemployment_motivation_on_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitemployment',
            name='cv_file',
            field=models.ImageField(blank=True, null=True, upload_to=submitemployment.models.cv_file_path),
        ),
    ]
