# Generated by Django 4.2.10 on 2024-02-27 00:06

from django.db import migrations, models
import submitemployment.models


class Migration(migrations.Migration):

    dependencies = [
        ('submitemployment', '0003_submitemployment_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitemployment',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=submitemployment.models.cv_file_path),
        ),
    ]
