# Generated by Django 4.2.10 on 2024-02-28 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_profile_description'),
        ('submitemployment', '0004_alter_submitemployment_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitemployment',
            name='submiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
